spring:
  application:
    name: TradeMatching
  data:
    mongodb:
      uri: mongodb://localhost:32771
      database: matching
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,mappings

app:
  accounts:
    groups:
      - name: All-in-one
        accounts:
      - name: Left
        accounts: a
      - name: Right
        accounts: b,c