spring:
  application:
    name: TradeMatching

server:
  port: 80

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health,beans,mappings
  endpoint:
    health:
      show-details: always


app:
  accounts:
    groups:
      - name: All-in-one
        accounts:
      - name: Left
        accounts: a
      - name: Right
        accounts: b,c