spring:
  application:
    name: ReactivePlayground
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,mappings

app:
  accounts:
    groups:
      - name: All-in-one
        accounts:
      - name: Left
        accounts: a
      - name: Right
        accounts: b,c