version: 2
jobs:
  build:
    working_directory: ~/trade-matching
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - restore_cache:
          key: trade-matching-{{ checksum "build.gradle.kts" }}
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: trade-matching-{{ checksum "build.gradle.kts" }}

      - run: gradle test bootJar
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/libs/trade-matching-1.0-SNAPSHOT.jar

      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --tag=trade-matching:$TAG .
#          use gcloud CLI push image later
